force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AN-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Review__c.field-meta.xml
<CustomField>
    <fullName>Review__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Review</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Close_Date__c</fullName>
    <label>Close Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/No_of_Openings__c.field-meta.xml
<CustomField>
    <fullName>No_of_Openings__c</fullName>
    <defaultValue>1</defaultValue>
    <label>No. of Openings</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReviewHandlerTest.cls
@isTest
public class ReviewHandlerTest {
    
    @isTest 
    static void testPreventReviews() {
        System.runAs(runTestAsUser())
        {
            // Create a sample application with 'Rejected' status
            Application__c rejectedApp = new Application__c(Status__c='Rejected');
            insert rejectedApp;
            
            // Create a review for the rejected application
            Review__c review = new Review__c(Application__c=rejectedApp.Id, Status__c='On Hold',Rating__c=8);
            boolean flag=false;
            // Try inserting the review
            try {
                insert review;
                // Ensure the review was not inserted for a rejected application
                System.assert(false, 'Review should not have been inserted for a rejected application');
                flag=true;
            } catch (DmlException e) {
                // Expecting an error due to the rejected application
                System.assertEquals(1, e.getNumDml());
                // Retrieve and check the error messages
                String errorMessage = e.getDmlMessage(0);
                System.assert(errorMessage.contains(System.label.reviewstatus));
            }
            
            // Clean up after the test
            if(flag){
                delete review;
            }
        }
    }
    
    @isTest
    static void testPreventMultipleReviews() {
        System.runAs(runTestAsUser())
        {
            Position__c position=new Position__c(Name='Test Position',Close_Date__c=System.today()-1);
            insert position;
            String currentUser=[Select id from user where Username=: UserInfo.getUserName()].id;
            
            Candidate__c cand=new Candidate__c(Name='Jung',Email__c='Test@usermail.com',user__c=currentUser);
            Insert cand;
            // Create a sample application
            Application__c application = new Application__c(Position__c=position.Id,Candidate__c=cand.Id,status__c='Approved');
            insert application;
            
            // Create two reviews for the same application
            Review__c review1 = new Review__c(Application__c=application.Id,Rating__c=8);
            Review__c review2 = new Review__c(Application__c=application.Id,Rating__c=9);
            
            // Try inserting the reviews
            try {
                insert new List<Review__c>{review1, review2};
                    // Ensure the second review was not inserted for the same application
                    
                    } catch (DmlException e) {
                        // Expecting an error due to the second review for the same application
                        System.assertEquals(2, e.getNumDml());
                        
                        // Retrieve and check the error messages for both DML operations
                        String errorMessage1 = e.getDmlMessage(0);
                        String errorMessage2 = e.getDmlMessage(1);
                        
                        // Check if either of the error messages contains the expected message
                        System.assert(
                            errorMessage1.contains(System.label.reviewrepeat) ||
                            errorMessage2.contains(System.label.reviewrepeat)
                        );
                        
                    }
            
            // Clean up after the test
            delete review1;
        }
    }
    
    @isTest
    static void testUpdatePositions() {
        System.runAs(runTestAsUser())
        {
            // Create a sample application
            Position__c pos=new Position__c(Name='Jung',Close_Date__c=System.today()+1);
            insert pos;
            String currentUser=[Select id from user where Username=: UserInfo.getUserName()].id;
            Candidate__c candidate=new Candidate__c(Name='Shekhar',Email__c='xyz@abc.com',user__c=currentUser);
            insert candidate;
            Application__c application = new Application__c(Status__c='Approved', Position__c = pos.id,Candidate__c=candidate.id);
            insert application;
            
            // Create a review for the application
            Review__c review = new Review__c(Application__c=application.Id,Rating__c=8);
            insert review;
            review.Status__c='Hired';
            update review;
            
            // Ensure the position's No_Of_Openings__c is updated
            Position__c position = [SELECT Id, No_Of_Openings__c FROM Position__c WHERE Id = :application.Position__c];
            System.assertEquals(0, position.No_Of_Openings__c); // Adjust the expected value based on your data
            
            // Clean up after the test
            delete review;
        }
    }
    
    @isTest
    static void testHandleReviewInsert() {
        System.runAs(runTestAsUser())
        {
            
            Position__c position=new Position__c(Name='Test Position',Close_Date__c=System.today()-1);
            insert position;
            String currentUser=[Select id from user where Username=: UserInfo.getUserName()].id;
            Candidate__c cand=new Candidate__c(Name='Jung',Email__c='Test@usermail.com',user__c=currentUser);
            Insert cand;
            
            // Create a sample application
            
            Application__c application = new Application__c(Candidate__c=cand.Id,Position__c=position.id,Status__c='Approved');
            insert application;
            
            // Create a review for the application
            Review__c review = new Review__c(Application__c=application.Id,Rating__c=9,Status__c='On Hold');
            
            // Insert the review - this will trigger the handler's method indirectly
            insert review;
            
            // Ensure the application's Review__c field is updated
            Application__c updatedApplication = [SELECT Id, Review__c FROM Application__c WHERE Id = :application.Id];
            System.assertEquals(true, updatedApplication.Review__c);
            
            // Clean up after the test
            delete review;
        }
    }
    
    // Helper method to set up the user context and run test methods
    private static user runTestAsUser() {
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'Interview Parties 2'];  
        
        
        // Assuming 'YourPermissionSetName' is the API name of the permission set you want to assign
        PermissionSet permSet = [SELECT Id FROM PermissionSet WHERE Name = 'Candidate_2'];
        
        User testUser = new User(
            Alias = 'testUser',
            Email = 'testuser@example.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = profile.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'kshitiz@gupta.com'
        );
        
        insert testUser;
        // Assign the permission set to the user
        PermissionSetAssignment psa = new PermissionSetAssignment(
            PermissionSetId = permSet.Id,
            AssigneeId = testUser.Id
        );
        insert psa;
        
        return testUser;
        
        
    }
    
    
    
    
}